# Generated by Django 5.2.1 on 2025-05-10 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellnessentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wellnessentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wellnessentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('sleep', 'Sleep'), ('water', 'Water Intake'), ('meditation', 'Meditation'), ('skincare', 'Skincare'), ('reading', 'Reading'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellnessentry',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_value',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnessentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
