# Generated by Django 5.2.1 on 2025-05-10 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='healthtip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wellnessentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wellnessentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'created_at'], name='tracker_hab_user_id_df800c_idx'),
        ),
        migrations.AddIndex(
            model_name='healthtip',
            index=models.Index(fields=['category', 'created_at'], name='tracker_hea_categor_e26926_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessentry',
            index=models.Index(fields=['habit', 'date'], name='tracker_wel_habit_i_91d87b_idx'),
        ),
    ]
